CI:
  - ".github/**/**"

migrations:
  - app/AI4Green4Students/Migrations/*.cs

frontend:
  - app/client-app/**/*

backend:
  - app/AI4Green4Students/**/*

workers:
  - app/workers/**/*

tests:
  - AI4Green4Students.Test/**/*
