env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/warnings
parserOptions:
  ecmaVersion: 2021
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  react/react-in-jsx-scope: 0
  react/jsx-uses-react: 0
  react/prop-types: 0
  import/no-duplicates: error
