name: ai4green4students

services:
  db-ai4green4students:
    container_name: db-ai4green4students
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ai4green4students

  db-ai4green:
    container_name: db-ai4green
    image: postgres:13
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ai4green

  azurite:
    container_name: azurite-ai4green4students
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: "none"
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  keycloakdb:
    image: postgres:13
    restart: always
    ports:
      - 5434:5432
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
      POSTGRES_DB: keycloak

  keycloak:
    image: docker.io/bitnami/keycloak:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_HOST: keycloakdb
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak_user
      KEYCLOAK_DATABASE_PASSWORD: keycloak_password
    depends_on:
      - keycloakdb

volumes:
  keycloak_data:
    driver: local
