name: ai4green4students

services:
  db-ai4green4students:
    container_name: db-ai4green4students
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ai4green4students

  db-ai4green:
    container_name: db-ai4green
    image: postgres:13
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ai4green

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pepa-linha

  azurite:
    container_name: azurite-ai4green4students
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

