def smiles_symbols(
    compound: str,
) -> (
    str
):  # restores the sharp plus and minus symbols from the string generated by marvinJS
    return compound.replace("minus", "-").replace("plus", "+").replace("sharp", "#")