name: Build AI4Green4Students API

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - app/AI4Green4Students/**
      - .github/workflows/build.ai4green4students-api.yml

env:
  CI_build-config: release
  CI_dotnet-version: 8.0.x
  CI_project: ./app/AI4Green4Students/AI4Green4Students.csproj

  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.CI_dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.CI_project }}

      - name: Build
        run: >-
          dotnet build
          ${{ env.CI_project }}
          --no-restore
          -c ${{ env.CI_build-config }}
