name: Deploy AI4Green4Students Workers

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  CI_worker-project: ./app/workers
  CI_python-version: 3.12

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ env.CI_python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.CI_python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install uv
        run: pip install uv

      - name: Resolve dependencies
        working-directory: ${{ env.CI_worker-project }}
        run: |
          uv pip compile pyproject.toml --output-file requirements.txt

      - name: Install dependencies
        working-directory: ${{ env.CI_worker-project }}
        run: |
          uv pip sync requirements.txt --target "./.python_packages/lib/site-packages"

      - name: Prepare worker artifact
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: "zip"
          filename: "workers.zip"
          path: ${{ env.CI_worker-project }}
          directory: .

      - name: Publish workers artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./workers.zip
          name: workers
          retention-days: 1

  deploy-uat:
    name: Deploy UAT
    needs: [publish]
    runs-on: ubuntu-latest
    environment: uat

    steps:
      - name: Download worker artifact
        uses: actions/download-artifact@v4
        with:
          name: workers
          path: .

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WORKER_NAME }}
          package: ./workers.zip

  deploy-prod:
    name: Deploy Production
    needs: [publish]
    runs-on: ubuntu-latest
    environment: prod
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download worker artifact
        uses: actions/download-artifact@v4
        with:
          name: workers
          path: .

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WORKER_NAME }}
          package: ./workers.zip
