name: Validate Workers dependencies

on:
  pull_request:
    branches: [test]
    paths:
      - app/az-functions/**
      - .github/workflows/validate.workers-dependencies.yml

jobs:
  validate-dependencies:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        working-directory: app/az-functions
        run: |
          uv pip compile pyproject.toml --output-file requirements.txt
          uv pip sync requirements.txt --system
